// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddKey(arg1:string,arg2:string,arg3:string,arg4:number):Promise<Record<string, any>>;

export function BindChannelModels(arg1:number,arg2:Array<number>):Promise<string>;

export function BindModel(arg1:number,arg2:string,arg3:string,arg4:boolean):Promise<Record<string, any>>;

export function ConnectToNetwork():Promise<string>;

export function CreateChannel(arg1:string,arg2:string,arg3:string,arg4:number,arg5:Array<any>):Promise<Record<string, any>>;

export function CreateCombo(arg1:string,arg2:Array<string>,arg3:string,arg4:number):Promise<Record<string, any>>;

export function CreateModelSpec(arg1:Record<string, any>):Promise<Record<string, any>>;

export function CreateNodeApiKey(arg1:string):Promise<Record<string, any>>;

export function CreateWallet(arg1:string):Promise<Record<string, any>>;

export function DeleteChannel(arg1:number):Promise<string>;

export function DeleteCombo(arg1:string):Promise<string>;

export function DeleteKey(arg1:number):Promise<string>;

export function DeleteModelSpec(arg1:number):Promise<string>;

export function DeleteNodeApiKey(arg1:number):Promise<string>;

export function DisconnectFromNetwork():Promise<string>;

export function ExportSeed():Promise<Record<string, any>>;

export function FetchCatalogChannels():Promise<Array<Record<string, any>>>;

export function FetchCatalogModels():Promise<Array<Record<string, any>>>;

export function FetchCatalogProviders():Promise<Array<Record<string, any>>>;

export function FetchPeerCount():Promise<number>;

export function GetConfig():Promise<Record<string, any>>;

export function GetPlatformURL():Promise<string>;

export function GetRecentRequests(arg1:number):Promise<Array<Record<string, any>>>;

export function GetTunnelUsage():Promise<Record<string, any>>;

export function GetUsageLogs(arg1:number):Promise<Array<Record<string, any>>>;

export function GetUsageStats():Promise<Record<string, any>>;

export function JoinNetwork(arg1:string):Promise<string>;

export function LeaveNetwork():Promise<string>;

export function ListBindings():Promise<Array<Record<string, any>>>;

export function ListChannelModels(arg1:number):Promise<Array<Record<string, any>>>;

export function ListChannels():Promise<Array<Record<string, any>>>;

export function ListCombos():Promise<Array<Record<string, any>>>;

export function ListKeys():Promise<Array<Record<string, any>>>;

export function ListModelSpecs():Promise<Array<Record<string, any>>>;

export function ListNodeApiKeys():Promise<Array<Record<string, any>>>;

export function NetworkStatus():Promise<Record<string, any>>;

export function Ping():Promise<string>;

export function SaveConfig(arg1:Record<string, any>):Promise<string>;

export function SetupWallet():Promise<Record<string, any>>;

export function Status():Promise<Record<string, any>>;

export function Stop():Promise<string>;

export function UnbindChannelModel(arg1:number):Promise<string>;

export function UnbindModel(arg1:number):Promise<string>;

export function UpdateChannel(arg1:number,arg2:string,arg3:Array<any>,arg4:string):Promise<Record<string, any>>;

export function WalletStatus():Promise<Record<string, any>>;
