// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddKey(arg1, arg2, arg3, arg4) {
  return window['go']['main']['NodeService']['AddKey'](arg1, arg2, arg3, arg4);
}

export function BindChannelModels(arg1, arg2) {
  return window['go']['main']['NodeService']['BindChannelModels'](arg1, arg2);
}

export function BindModel(arg1, arg2, arg3, arg4) {
  return window['go']['main']['NodeService']['BindModel'](arg1, arg2, arg3, arg4);
}

export function ConnectToNetwork() {
  return window['go']['main']['NodeService']['ConnectToNetwork']();
}

export function CreateChannel(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['NodeService']['CreateChannel'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateCombo(arg1, arg2, arg3, arg4) {
  return window['go']['main']['NodeService']['CreateCombo'](arg1, arg2, arg3, arg4);
}

export function CreateModelSpec(arg1) {
  return window['go']['main']['NodeService']['CreateModelSpec'](arg1);
}

export function CreateNodeApiKey(arg1) {
  return window['go']['main']['NodeService']['CreateNodeApiKey'](arg1);
}

export function CreateWallet(arg1) {
  return window['go']['main']['NodeService']['CreateWallet'](arg1);
}

export function DeleteChannel(arg1) {
  return window['go']['main']['NodeService']['DeleteChannel'](arg1);
}

export function DeleteCombo(arg1) {
  return window['go']['main']['NodeService']['DeleteCombo'](arg1);
}

export function DeleteKey(arg1) {
  return window['go']['main']['NodeService']['DeleteKey'](arg1);
}

export function DeleteModelSpec(arg1) {
  return window['go']['main']['NodeService']['DeleteModelSpec'](arg1);
}

export function DeleteNodeApiKey(arg1) {
  return window['go']['main']['NodeService']['DeleteNodeApiKey'](arg1);
}

export function DisconnectFromNetwork() {
  return window['go']['main']['NodeService']['DisconnectFromNetwork']();
}

export function ExportSeed() {
  return window['go']['main']['NodeService']['ExportSeed']();
}

export function FetchCatalogChannels() {
  return window['go']['main']['NodeService']['FetchCatalogChannels']();
}

export function FetchCatalogModels() {
  return window['go']['main']['NodeService']['FetchCatalogModels']();
}

export function FetchCatalogProviders() {
  return window['go']['main']['NodeService']['FetchCatalogProviders']();
}

export function FetchPeerCount() {
  return window['go']['main']['NodeService']['FetchPeerCount']();
}

export function GetConfig() {
  return window['go']['main']['NodeService']['GetConfig']();
}

export function GetPlatformURL() {
  return window['go']['main']['NodeService']['GetPlatformURL']();
}

export function GetRecentRequests(arg1) {
  return window['go']['main']['NodeService']['GetRecentRequests'](arg1);
}

export function GetTunnelUsage() {
  return window['go']['main']['NodeService']['GetTunnelUsage']();
}

export function GetUsageLogs(arg1) {
  return window['go']['main']['NodeService']['GetUsageLogs'](arg1);
}

export function GetUsageStats() {
  return window['go']['main']['NodeService']['GetUsageStats']();
}

export function JoinNetwork(arg1) {
  return window['go']['main']['NodeService']['JoinNetwork'](arg1);
}

export function LeaveNetwork() {
  return window['go']['main']['NodeService']['LeaveNetwork']();
}

export function ListBindings() {
  return window['go']['main']['NodeService']['ListBindings']();
}

export function ListChannelModels(arg1) {
  return window['go']['main']['NodeService']['ListChannelModels'](arg1);
}

export function ListChannels() {
  return window['go']['main']['NodeService']['ListChannels']();
}

export function ListCombos() {
  return window['go']['main']['NodeService']['ListCombos']();
}

export function ListKeys() {
  return window['go']['main']['NodeService']['ListKeys']();
}

export function ListModelSpecs() {
  return window['go']['main']['NodeService']['ListModelSpecs']();
}

export function ListNodeApiKeys() {
  return window['go']['main']['NodeService']['ListNodeApiKeys']();
}

export function NetworkStatus() {
  return window['go']['main']['NodeService']['NetworkStatus']();
}

export function Ping() {
  return window['go']['main']['NodeService']['Ping']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['NodeService']['SaveConfig'](arg1);
}

export function SetupWallet() {
  return window['go']['main']['NodeService']['SetupWallet']();
}

export function Status() {
  return window['go']['main']['NodeService']['Status']();
}

export function Stop() {
  return window['go']['main']['NodeService']['Stop']();
}

export function UnbindChannelModel(arg1) {
  return window['go']['main']['NodeService']['UnbindChannelModel'](arg1);
}

export function UnbindModel(arg1) {
  return window['go']['main']['NodeService']['UnbindModel'](arg1);
}

export function UpdateChannel(arg1, arg2, arg3, arg4) {
  return window['go']['main']['NodeService']['UpdateChannel'](arg1, arg2, arg3, arg4);
}

export function WalletStatus() {
  return window['go']['main']['NodeService']['WalletStatus']();
}
