gfcli:
  gen:
    dao:
      - link: "pgsql:aiplatform:aiplatform@tcp(127.0.0.1:5432)/ai_platform"
        path: "./internal"
        descriptionTag: true
        noJsonTag: false
        noModelComment: false
        clear: false
        prefix: ""
        removePrefix: ""
        jsonCase: "CamelLower"
